config/routes.rb
Rails.application.routes.draw do
  get 'principal/index'
  root 'principal#index'
  
  get 'principal/sobre'

  get 'principal/contato'
  post 'principal/contato'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/principal_controller.rb
class PrincipalController < ApplicationController
  def index
  end

  def sobre
  end

  def contato
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/principal_helper.rb
module PrincipalHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application'%>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/principal/contato.html.erb
<!DOCTYPE HTML>
<!--
	Template obtido do site HTML5 UP e modificado por Guilherme Olier @OlierG.
	Landed by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>G Olier - Contato</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
		<link rel="stylesheet" href="assets/css/main.css" />
		<!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
		<!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
	</head>
	<body>
		<div id="page-wrapper">

			<!-- Header -->
				<header id="header">
					<h1 id="logo"><%= link_to "Portfólio", root_path %></h1>
					<nav id="nav">
						<ul>
							<li><%= link_to "Home", root_path %></li>
							<li><%= link_to "Sobre Mim", principal_sobre_path %></li>
							<li><%= link_to "Contato", principal_contato_path %></li>
						</ul>
					</nav>
				</header>

			<!-- Main -->
				<div id="main" class="wrapper style1">
					<div class="container">


						<!-- Text -->
							<section>
								<h3>Contato</h3>
								<p>Entre em contato pelas redes sociais ou pelos números.</p>

								<p>
								<strong>Skype:</strong> GuiOlier <br/>
								<strong>LinkedIn:</strong> Guilherme Olier <br/>
								<strong>Email:</strong> prado.olier@gmail.com
								</p>
														
								<p><strong>Vivo:</strong> (11) 9.9881-6305  (Whatsapp)<br/>
								<strong>Fixo:</strong> (11) 4411-6779 (Recados) </p>
								<hr />
					</div>
				</div>
			<!-- Footer -->
				<footer id="footer">	
					<ul class="icons">

						<li><a href="https://www.facebook.com/GuiOlier"><img src="http://icon-icons.com/icons2/693/PNG/512/Facebook_Rounded_Solid_icon-icons.com_61562.png" height="50" width="50"></a></li>

						<li><a href="https://br.linkedin.com/in/guiherme-olier"><img src="http://icon-icons.com/icons2/693/PNG/512/LinkedIn_Rounded_Solid_icon-icons.com_61559.png" height="50" width="50"></a></li>

						<li><a href="https://br.pinterest.com/GuiOlier/"><img src="http://icon-icons.com/icons2/693/PNG/512/Pinterest_Rounded_Solid_icon-icons.com_61557.png" height="50" width="50"></a></li>

						<li><a href="https://github.com/GuiOlier/"><img src="http://icon-icons.com/icons2/510/PNG/512/social-github_icon-icons.com_50019.png" height="50" width="50"></a></li>
					</ul>
					<ul class="copyright">
						<li>&copy; Untitled. All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
						<li>Editado por Guilherme Olier</li>
					</ul>
				</footer>

		</div>

		<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/jquery.scrolly.min.js"></script>
			<script src="assets/js/jquery.dropotron.min.js"></script>
			<script src="assets/js/jquery.scrollex.min.js"></script>
			<script src="assets/js/skel.min.js"></script>
			<script src="assets/js/util.js"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="assets/js/main.js"></script>

	</body>
</html>

app/views/principal/index.html.erb
<!DOCTYPE HTML>
<!--
	Template obtido do site HTML5 UP e modificado por Guilherme Olier @OlierG.
	Landed by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>G Olier - Home</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
		<link rel="stylesheet" href="assets/css/main.css" />
		<!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
		<!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
	</head>
	<body class="landing">
		<div id="page-wrapper">

			<!-- Header -->
				<header id="header">
					<h1 id="logo"><%= link_to "Portfólio", root_path %></h1>
					<nav id="nav">
						<ul>
							<li><%= link_to "Home", root_path %></li>
							<li><%= link_to "Sobre Mim", principal_sobre_path %></li>
							<li><%= link_to "Contato", principal_contato_path %></li>
						</ul>
					</nav>
				</header>

			<!-- Banner -->
				<section id="banner">
					<div class="content">
						<header>
							<h2>Guilherme Olier</h2>
							<h3>Estudante de ADS</h3>
							<p><a href="#one"><img src="https://cedcn.org/wp-content/themes/cedcn/images/icon-arrow_dropdown.svg" align="center" height="50" width="50"></a></p>
						</header>
						<span class="image"><img src="https://s-media-cache-ak0.pinimg.com/564x/b6/ba/6d/b6ba6d3795de7ae83329af1c67810d50.jpg" alt="" /></span>


					</div>


					
				</section>

			<!-- One -->
				<section id="one" class="wrapper special fade">
					<div class="container">
						<header>
							<h2>Habilidades</h2>
							<p>Alguns de meus conhecimentos. <p>
						</header>
						

						<div class="content">
							<div class="container">
								<div class="row">

									<div class="4u 12u$(medium)">
										<header>
											<ul> 
											<li> HTML5 (Intermediário)</li>
											<li> CSS3 (Intermediário)</li>
											<li> JavaScript (Básico)</li>
											<li> Bootstrap (Básico)</li>
											<li> Heroku (Intermediário)</li>
											</ul>
										</header>
									</div>

									<div class="4u 12u$(medium)">
										<header>
											<ul> 
											<li> Ruby (Básico)</li>
											<li> Python (Básico)</li>
											<li> C Sharp (Básico) </li>
											<li> Ruby On Rails (Intermediário)</li>
											</ul>
										</header>
									</div>

									<div class="4u 12u$(medium)">
										<header>
											<ul> 
											<li> MySQL (Intermediário)</li>
											<li> PostgreSQL (Básico)</li>
											<li> GNU/Linux (Básico)</li>
											<li> Git/Github (Intermediário)</li>
											<li> Photoshop CS6 (Básico)</li>
											</ul>
										</header>
									</div>

								</div>
							</div>
						</div>

					<p><a href="#two"><img src="https://cedcn.org/wp-content/themes/cedcn/images/icon-arrow_dropdown.svg" align="center" height="50" width="50"></a></p> 

				</section>

				<hr>
			<!-- Two -->
				<section id="two" class="style2 bottom">
					<div class="content">
						<div class="container">
							<div class="row">

								<div class="4u 12u$(medium)">
									<header>
										</br>
										<h2>Louco por programação</h2>
										<p>O amor é lindo, imagine sobre trilhos.<p>
									</header>
								</div>
								<div class="4u 12u$(medium)">
									<p> Com 17 anos realizei um sonho, ingressei no Instituto Federal para cursar Análise e Desenv. de sistemas, uma oportunidade para focar e desenvolver minhas habilidades e paixões. Já no IFSP, fui convidado a participar de uma equipe de Iniciação Científica pela universidade.</p>
								</div>
								<div class="4u$ 12u$(medium)">
									<p>Aceitei o convite e hoje faço parte de um time que supervisionados por uma professora orientadora e minha tutora pessoal, desenvolve uma plataforma web service para auxiliar deficientes visuais no processo de aprendizagem, dentro da TI.</p>
								</div>
							</div>
						</div>
					</div>
				</section>

			<!-- Footer -->
				<footer id="footer">
					<ul class="icons">

						<li><a href="https://www.facebook.com/GuiOlier"><img src="http://icon-icons.com/icons2/693/PNG/512/Facebook_Rounded_Solid_icon-icons.com_61562.png" height="50" width="50"></a></li>

						<li><a href="https://br.linkedin.com/in/guiherme-olier"><img src="http://icon-icons.com/icons2/693/PNG/512/LinkedIn_Rounded_Solid_icon-icons.com_61559.png" height="50" width="50"></a></li>

						<li><a href="https://br.pinterest.com/GuiOlier/"><img src="http://icon-icons.com/icons2/693/PNG/512/Pinterest_Rounded_Solid_icon-icons.com_61557.png" height="50" width="50"></a></li>

						<li><a href="https://github.com/GuiOlier/"><img src="http://icon-icons.com/icons2/510/PNG/512/social-github_icon-icons.com_50019.png" height="50" width="50"></a></li>
						<a href="#banner"><img src="https://www.sbo.net/sports-map/img/top_arrow.png" align="right" height="50" width="50"></a>
					</ul>
					<ul class="copyright">
						<li>&copy; Untitled. All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
						<li>Editado por Guilherme Olier</li>
					</ul>
				</footer>

		</div>

		<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/jquery.scrolly.min.js"></script>
			<script src="assets/js/jquery.dropotron.min.js"></script>
			<script src="assets/js/jquery.scrollex.min.js"></script>
			<script src="assets/js/skel.min.js"></script>
			<script src="assets/js/util.js"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="assets/js/main.js"></script>

	</body>
</html>

app/views/principal/sobre.html.erb
<!DOCTYPE HTML>
<!--
	Template obtido do site HTML5 UP e modificado por Guilherme Olier @OlierG.
	Landed by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>G Olier - Sobre</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
		<link rel="stylesheet" href="assets/css/main.css" />
		<!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
		<!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
	</head>
	<body>
		<div id="page-wrapper">

			<!-- Header -->
				<header id="header">
					<h1 id="logo"><%= link_to "Portfólio", root_path %></h1>
					<nav id="nav">
						<ul>
							<li><%= link_to "Home", root_path %></li>
							<li><%= link_to "Sobre Mim", principal_sobre_path %></li>
							<li><%= link_to "Contato", principal_contato_path %></li>
						</ul>
					</nav>
				</header>

			<!-- Main -->
				<div id="main" class="wrapper style1">
					<div class="container">
						<header class="major">
							<h2>Guilherme Olier</h2>
							<p>Currículo Online</p>
						</header>

						<!-- Text -->
							<section>
								<h2> Formação Acadêmica </h2>
								<h3>Instituto Federal de Educação, Ciências e Tecnologia</h3>
								<p>Tecnologia em Análise e Desenvolvimento de Sistemas <br/>
								Segundo semestre - Campus Bragança Paulista<br/>
								Jan/2016 - Dez/2018</p>

								<h3>Centro de Formação Profissional Atibaia</h3>
								<p>Técnico em Logística Empresarial <br/>
								2015 </p>

								<hr />

								<header>
									<h2>Experiência Profissional</h2>
										<h3>SOS UseGuinchos</h3>
										<p>Auxiliar Administrativo/Operacional</p>
								</header>
								<p>Dentre as responsabilidades, estavam: Contato direto com clientes, recebimento de ordens de serviço, gerenciamento de disponibilidade, análise de custo, coordenação de pessoal ativo, emissão de nota etc. <br/> 
								Responsável pelo projeto e implantação de processos pertinentes a área. Redução de custos da área de 25% após conclusão. </p>

								<header>
									<h3> Bar e Restaurante Barão</h3>
										<p> Garçom/Auxiliar de Cozinha.</p>
								</header>
								<p> Principais atividades: Contato direto com clientes, preparo de bebidas, encaminhamento de pedidos, reposição de itens e utensílios, organização e limpeza do salão e Buffet, tratamento de contas e pagamentos. </p>
							</section>
					</div>
				</div>



			<!-- Footer -->
				<footer id="footer">
					<ul class="icons">

						<li><a href="https://www.facebook.com/GuiOlier"><img src="http://icon-icons.com/icons2/693/PNG/512/Facebook_Rounded_Solid_icon-icons.com_61562.png" height="50" width="50"></a></li>

						<li><a href="https://br.linkedin.com/in/guiherme-olier"><img src="http://icon-icons.com/icons2/693/PNG/512/LinkedIn_Rounded_Solid_icon-icons.com_61559.png" height="50" width="50"></a></li>

						<li><a href="https://br.pinterest.com/GuiOlier/"><img src="http://icon-icons.com/icons2/693/PNG/512/Pinterest_Rounded_Solid_icon-icons.com_61557.png" height="50" width="50"></a></li>

						<li><a href="https://github.com/GuiOlier/"><img src="http://icon-icons.com/icons2/510/PNG/512/social-github_icon-icons.com_50019.png" height="50" width="50"></a></li>
					</ul>
					<ul class="copyright">
						<li>&copy; Untitled. All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
						<li>Editado por Guilherme Olier</li>
					</ul>
				</footer>

		</div>

		<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/jquery.scrolly.min.js"></script>
			<script src="assets/js/jquery.dropotron.min.js"></script>
			<script src="assets/js/jquery.scrollex.min.js"></script>
			<script src="assets/js/skel.min.js"></script>
			<script src="assets/js/util.js"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="assets/js/main.js"></script>

	</body>
</html>